networks:
  juniors-bootcamp:
    driver: bridge

volumes:
  juniors-bootcamp-v1-data:
    driver: local

services:
  juniors-bootcamp-v1-database:
    image: mongo:latest
    restart: always
    container_name: juniors-bootcamp-v1-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:27017'
    volumes:
      - juniors-bootcamp-v1-data:/data/db
    networks:
      - juniors-bootcamp

  juniors-bootcamp-v1-service:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/siberiacancode/juniors-bootcamp-backend-v1
    container_name: juniors-bootcamp-backend-v1
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3011
      - SERVER_URL=${SERVER_URL}
      - DATABASE_URL=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@juniors-bootcamp-v1-database:27017/${DATABASE_NAME}?authSource=admin
    ports:
      - '3011:3011'
    depends_on:
      - juniors-bootcamp-v1-database
    networks:
      - juniors-bootcamp
